In [3]:
import pandas as pd
import numpy as np

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', np.nan, np.nan, 70000],
    [np.nan, 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [15]:
labels=['a','b','c','d']
df=pd.DataFrame(data_list,columns=labels)

df

       a   b         c      d
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [16]:
df.isna().sum()

a    0
b    0
c    0
d    0
dtype: int64

In [17]:
df.describe()

               b             d
count   4.000000      4.000000
mean   33.250000  70500.000000
std     6.396614  10214.368964
min    28.000000  62000.000000
25%    28.750000  64250.000000
50%    31.500000  67500.000000
75%    36.000000  73750.000000
max    42.000000  85000.000000

In [24]:
df=pd.DataFrame(data_list)
df

       0     1         2      3
0   John  28.0  New York  65000
1   Anna   NaN       NaN  70000
2    NaN  29.0    Berlin  62000
3  Linda  42.0    London  85000

In [25]:
df.fillna(0)

       0     1         2      3
0   John  28.0  New York  65000
1   Anna   0.0         0  70000
2      0  29.0    Berlin  62000
3  Linda  42.0    London  85000

In [30]:
df.dropna(thresh=3)

       0     1         2      3
0   John  28.0  New York  65000
2    NaN  29.0    Berlin  62000
3  Linda  42.0    London  85000

In [31]:
values={0:100,1:200,2:300,3:400}
df.fillna(value=values)

       0      1         2      3
0   John   28.0  New York  65000
1   Anna  200.0       300  70000
2    100   29.0    Berlin  62000
3  Linda   42.0    London  85000

In [5]:
df=pd.DataFrame(data_list)
df

       0     1         2      3
0   John  28.0  New York  65000
1   Anna   NaN       NaN  70000
2    NaN  29.0    Berlin  62000
3  Linda  42.0    London  85000