In [1]:
import numpy as np
import pandas as pd

In [14]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [7]:
df1['A'] +10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [10]:
df1.isna()

       A      B      C
0  False  False  False
1  False  False   True
2  False  False  False
3  False  False  False
4  False  False  False

In [11]:
df1.fillna(df1.mean())

   A   B      C
0  1  10  100.0
1  2  20  325.0
2  3  30  300.0
3  4  40  400.0
4  5  50  500.0

In [13]:
df1.dropna()

   A   B      C
0  1  10  100.0
2  3  30  300.0
3  4  40  400.0
4  5  50  500.0

In [15]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [16]:
df1.shape

(5, 3)

In [17]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
df1['B']=df1['B'].apply(lambda x: x**2)
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [21]:
df1['D']=df1['A'].apply(lambda x: x**2)

In [22]:
df1

   A        B    C   D
0  1    10000  100   1
1  2   160000  200   4
2  3   810000  300   9
3  4  2560000  400  16
4  5  6250000  500  25